//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson2_casino.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Casino_Vulkan0oEntities5 : DbContext
    {
        public Casino_Vulkan0oEntities5()
            : base("name=Casino_Vulkan0oEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<History_Of_Matches> History_Of_Matches { get; set; }
        public virtual DbSet<History_of_rounds> History_of_rounds { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Replenishment_transaction> Replenishment_transaction { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<rounds> rounds { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Withdrawal_Transaction> Withdrawal_Transaction { get; set; }
    }
}
